PREFIX localgov: <http://opendatacommunities.org/def/local-government/>
PREFIX admingeo: <http://opendatacommunities.org/ontology/admingeo/>
PREFIX os: <http://data.ordnancesurvey.co.uk/ontology/admingeo/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT * WHERE {
    ?opendatacommunities_uri rdf:type localgov:DevelopmentCorporation .
    { ?opendatacommunities_uri rdfs:label ?name }
    { ?opendatacommunities_uri os:gssCode ?statistical_geography}
    OPTIONAL { ?opendatacommunities_uri localgov:billingAuthorityCode ?billing_authority }
}
ORDER BY ASC(?name)
