name: Call Collection Run
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
jobs:
  call-workflow:
    uses: digital-land/collection-template/.github/workflows/callable_run.yml@main
    secrets: inherit
  build-package:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello world!

