name: Call Collection Run
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: null
jobs:
  call-workflow:
    steps:
      - uses: digital-land/collection-template/.github/workflows/callable_run.yml@main
        secrets: inherit
      - run: build-pagkage.sh
        secrets: inherit

